In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
import numpy as np

In [4]:
a = [1,2,3,4,5,6,7]

In [5]:
type(a)

list

In [6]:
a1 = np.array(a)

In [7]:
type(a1)

numpy.ndarray

In [8]:
a1.ndim

1

In [9]:
a1.shape

(7,)

In [10]:
a = np.array([[1,2,3],
             [4,5,6]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(a)

numpy.ndarray

In [13]:
a.ndim

2

In [14]:
a.shape

(2, 3)

In [15]:
(3,640,640)

(3, 640, 640)

In [16]:
a.dtype

dtype('int32')

In [17]:
a = np.ones(5)

In [18]:
a

array([1., 1., 1., 1., 1.])

In [19]:
a.dtype

dtype('float64')

In [20]:
a1 = np.ones(5, dtype=int)
a1

array([1, 1, 1, 1, 1])

In [21]:
a = np.ones((3,4,3))

In [22]:
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [23]:
a.ndim

3

In [24]:
a = np.zeros((2,3,4))

In [25]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
a = np.zeros((1,3,2))
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [27]:
a.ndim

3

In [28]:
a = np.zeros((1,3))

In [29]:
a

array([[0., 0., 0.]])

In [30]:
a.ndim

2

In [31]:
a = np.zeros((1,2) , dtype=bool)

In [32]:
a

array([[False, False]])

In [33]:
a = np.array([1,2,3,4,5,6,7,8,9,11])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [34]:
a = np.arange(1,11)

In [35]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a = np.arange(12,200,5)
a

array([ 12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,  67,  72,
        77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127, 132, 137,
       142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192, 197])

In [37]:
a = np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [38]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
a.reshape(5,3)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
a.ndim

1

In [41]:
len(a)

15

In [42]:
a.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [43]:
a = np.arange(1,25).reshape(3,8)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [44]:
a.ndim

2

In [45]:
b = np.arange(1,25).reshape(6,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24]]])

In [46]:
b.ndim

3

In [47]:
b = np.arange(1,25).reshape(2,4,3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [48]:
b.ndim

3

In [49]:
b = b.ravel()

In [50]:
a.ndim

2

In [51]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [52]:
b = b.flatten()

In [53]:
b.ndim

1

In [54]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [55]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [56]:
a.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [57]:
a = np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [58]:
a1 = a.reshape(2,4,3)
a1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [59]:
a1.ndim

3

In [60]:
a1 = a1.reshape(-1,1)
a1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [61]:
a1.ndim

2

In [62]:
a1 = a1.reshape(1,-1)
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [63]:
a1.ndim

2

In [64]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)


In [65]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a1 = np.add(a,b)
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [68]:
a1 = np.subtract(a,b)
a1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [69]:
a1 = np.divide(a,b)
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a.min()

1

In [72]:
a.max()

9

In [73]:
a.min(axis = 0)

array([1, 2, 3])

In [74]:
a.max(axis = 1)

array([3, 6, 9])

In [75]:
a1 = np.sum(a)
a1

45

In [76]:
a1 = np.argmax(a)

In [77]:
a1

8

In [78]:
np.argmin(a)

0

In [79]:
np.sum(a,axis = 0)

array([12, 15, 18])

In [80]:
np.sum(a,axis = 1)

array([ 6, 15, 24])

In [81]:
np.trace(a)

15

In [82]:
np.mean(a)

5.0

In [83]:
np.std(a)

2.581988897471611

In [84]:
np.var(a)

6.666666666666667

In [85]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [87]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [88]:
a = np.arange(1,101).reshape(10,10)

In [89]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [90]:
a[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [91]:
a[3:6]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [92]:
a[3:6,3]

array([34, 44, 54])

In [93]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [94]:
a[3:6,3:8]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [95]:
a[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [96]:
a[:,3:8]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78],
       [84, 85, 86, 87, 88],
       [94, 95, 96, 97, 98]])

In [97]:
a[:,3:10:2]

array([[  4,   6,   8,  10],
       [ 14,  16,  18,  20],
       [ 24,  26,  28,  30],
       [ 34,  36,  38,  40],
       [ 44,  46,  48,  50],
       [ 54,  56,  58,  60],
       [ 64,  66,  68,  70],
       [ 74,  76,  78,  80],
       [ 84,  86,  88,  90],
       [ 94,  96,  98, 100]])

In [98]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)

In [99]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [102]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [103]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)

In [104]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [105]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [106]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [108]:
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [109]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [110]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [111]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [112]:
np.split(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [113]:
np.split(a,4,axis=1)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [114]:
s = np.array([11,22,33,44,55,66,77])


In [115]:
s

array([11, 22, 33, 44, 55, 66, 77])

In [116]:
np.split(s,[2])

[array([11, 22]), array([33, 44, 55, 66, 77])]

In [117]:
np.split(s,[2,7])


[array([11, 22]), array([33, 44, 55, 66, 77]), array([], dtype=int32)]

In [118]:
np.random.random()

0.9346004876431017

In [119]:
np.random.random(5)

array([0.43924093, 0.81169967, 0.73153589, 0.89465908, 0.48764731])

In [120]:
s = np.random.random((3,3))

In [121]:
s.ndim

2

In [122]:
s = np.random.random((3,3,3))

In [123]:
s

array([[[0.55557473, 0.58299257, 0.63995231],
        [0.88378571, 0.62625359, 0.74672719],
        [0.37263613, 0.63856321, 0.92637462]],

       [[0.31187575, 0.84684119, 0.32417154],
        [0.8507981 , 0.92786556, 0.31721118],
        [0.03199932, 0.79277926, 0.25324594]],

       [[0.88664564, 0.12263654, 0.92374318],
        [0.73807306, 0.72401157, 0.53638677],
        [0.36405706, 0.83856671, 0.95299626]]])

In [124]:
s.ndim

3

In [131]:
a = np.linspace(1,15,25)
a

array([ 1.        ,  1.58333333,  2.16666667,  2.75      ,  3.33333333,
        3.91666667,  4.5       ,  5.08333333,  5.66666667,  6.25      ,
        6.83333333,  7.41666667,  8.        ,  8.58333333,  9.16666667,
        9.75      , 10.33333333, 10.91666667, 11.5       , 12.08333333,
       12.66666667, 13.25      , 13.83333333, 14.41666667, 15.        ])

In [132]:
b = np.random.choice(a,(2,2))

In [133]:
b

array([[14.41666667,  6.83333333],
       [ 3.91666667,  9.75      ]])

In [134]:
b.ndim

2

In [135]:
np.random.permutation(a)

array([ 1.        ,  8.58333333,  9.75      , 10.91666667,  1.58333333,
       12.08333333, 10.33333333, 12.66666667, 13.25      , 13.83333333,
        6.83333333,  5.08333333, 11.5       ,  2.16666667,  9.16666667,
       15.        ,  5.66666667,  3.91666667,  3.33333333,  2.75      ,
        7.41666667, 14.41666667,  4.5       ,  6.25      ,  8.        ])

In [140]:
a = np.random.uniform(1,100,25)
a

array([84.15604625, 10.17829635,  6.07012981, 53.28799871, 49.22782683,
       92.88307283, 46.66354547, 14.31682094,  3.71787753, 79.66663083,
       72.24442739, 99.84047023, 68.80001833,  2.86287847,  1.25662733,
        8.54257221, 97.75835497, 87.90327274,  2.33533013, 39.69273255,
       70.2104403 , 31.38642162, 90.82493939, 68.4767248 , 47.58025776])

In [141]:
b = np.random.normal(20,5,100)

In [144]:
b

array([18.67879456, 14.0232803 , 24.36150621, 10.25340604, 13.5359913 ,
       30.34725032, 20.08223966, 19.36788559, 17.82009811, 18.95721455,
       11.28900901, 15.34198294, 20.97361157,  6.32043068, 23.49772479,
       19.02394408, 20.79597995, 23.67133149, 24.0747688 , 17.6300618 ,
       20.63966543, 14.37174898, 14.02241259, 23.88039031, 17.56186591,
       13.42031127, 21.29146063, 25.05787221, 22.41341682, 21.04771579,
       17.18009601, 17.65641679, 25.56887825, 19.00864036, 19.20587204,
       19.75860974, 17.46223074, 23.77816002, 21.11139239, 22.39372752,
       23.84497747, 26.94689831, 18.59870582, 15.40513713, 16.78457817,
       22.85794447, 18.9928268 , 21.9559055 , 27.54882605, 16.37864737,
       19.68210715, 28.42585637, 18.15499643, 19.96083719, 21.47236518,
       15.70697714, 17.37325651, 13.72869505, 18.1708752 , 22.26778397,
       17.20496172, 21.36163319, 33.81125509, 21.85186381, 12.16251809,
       21.20483365, 18.44510597, 20.68028091, 21.09073278, 27.88

In [146]:
s = "python"
s1 = "data science"

In [147]:
s + s1

'pythondata science'

In [148]:
np.char.add(s , s1)

array('pythondata science', dtype='<U18')

In [150]:
np.char.upper(s1)

array('DATA SCIENCE', dtype='<U12')

In [151]:
np.char.split(s1)

array(list(['data', 'science']), dtype=object)

In [156]:
np.char.center(s,15,'*')

array('*****python****', dtype='<U15')